
title: Tejas Bhawari
logo: /headdhot portfolio.PNG
description: Data Analyst | RPA Consultant | Automation & Process Optimization | Driving Business Efficiency through Data & AI
#show_downloads: false
theme: jekyll-theme-minimal

