
title: Tejas Bhawari
logo: /headdhot portfolio.PNG
description: Data Analyst | RPA Developer | Automation & Process Optimization | Power BI | SQL | DAX | Driving Business Efficiency through Data & AI
show_downloads: false
theme: jekyll-theme-minimal
